const express=require("express")
const controller=require("../controllers/UserContoller")
const jwtmiddleware=require("../middelwares/jwtmiddleware")
const imageMiddleware=require("../middelwares/imageMiddleware")
const {searchUser}=require("../controllers/SearchController")
const router=express.Router()
router.post("/register",imageMiddleware.single("profilepic"),controller.createUser)
router.post("/verifyOtp",controller.VerifyOtp)
router.post("/login",controller.userLogin)
router.post("/updateOtp",controller.update)
router.get("/getUsers",jwtmiddleware.verifyToken,controller.getUser)
router.get("/search",jwtmiddleware.verifyToken,searchUser)
router.put("/updateprofile",jwtmiddleware.verifyToken,imageMiddleware.single("profilepic"),controller.updateProfile)
module.exports=router